# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 61bb35041ff9db81f46379b4d7b0f940ab8a162838e70b9b80d154750fdfbd96c128de9c164bd89bc5a7e26420b8a2c98823fe589c8c96c69f0c2dd148154305

test:
  secret_key_base: f1ccf2cd86116f266fcc449e5e1cdec26b8593113331c09ccb964136abb37e60a006b356c97591aef8635ccd93c15f9863818ac46efc55415c4ec52d90ee5966

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
